### PR TITLE
Fix issue where after.insert is handling collection with Mongo.ObjectID _id

### LINKED ISSUE #195: _id format on after.insert
There is a different behavior between version 1.3 and 1.4 of Meteor,  on after.insert the _id attribute of document is in mongo format, not in meteor format, it's correct?

Thanks

### PR DESCRIPTION
**Pull request by mbanting**
Fixes #195

### CODE REVIEW

**Comment by matb33** [comment]
This is great, and looks good to me. Thank you so much @mbanting

**Comment by mbanting** [comment]
You're welcome @matb33!

**Comment by mbanting** [comment]
@matb33 can you push this to Atmosphere when you get the chance? Thanks in advance!

**Comment by matb33** [comment]
Done :)

**Comment by mbanting** [comment]
Thank you!

**Pull request merged**
