### PR TITLE
Moved getUserId() to  CollectionHooks.getUserId()

### PR DESCRIPTION
**Pull request by cristo-rabani**
It will be nice if getUserId() function will be accessible from outside.
I make functionality with using your package and I don't want wraps second time doing the same like you do in Meteor.publish. I hope that it isn't any problem ?

### CODE REVIEW

**Comment by matb33** [comment]
Out of curiosity, is there a reason you are using that `getUserId()` instead of `Meteor.userId()`?

**Comment by mizzao** [comment]
Probably to access it during `Meteor.publish`. I think I had this case as well, but I managed to use it entirely from the hook provided `userId`.

**Comment by cristo-rabani** [comment]
I made method that can be used in Meteor.Publish as well.
Waiting killed my patience, and I have already implemented the same wrapping function on Meteor.Publish as this plugin. Potentially one relation less.

**Comment by matb33** [comment]
I was publishing a bug fix and remembered that you had asked for this -- I quickly added it to 0.7.13

**Pull request closed without merging**
