### PR TITLE
Throwing exceptions (part 2)

### PR DESCRIPTION
**Pull request by aramk**
This is a continuation of https://github.com/matb33/meteor-collection-hooks/pull/68. I've merged in the latest master and added a simple test. I think it's a useful addition and I'm currently using it for adding validation rules by throwing exceptions in hooks.

### CODE REVIEW

**Comment by matb33** [comment]
It's been busy on my end -- I will look at this as soon as I can. Thank you for the pull request!

**Comment by aramk** [comment]
Sure that's understandable :)

**Comment by matb33** [comment]
I ended up implementing this line-by-line in 0.7.15, while referring to your implementation and making changes as needed. Your work is very much appreciated -- it made it so much easier to implement. I've added your name to the Contributors section as well.

**Comment by aramk** [comment]
:+1: awesome thanks for that!

**Pull request closed without merging**
